/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Entity.Card;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Yatharth
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        idPassPanel = new javax.swing.JPanel();
        cardNumber = new javax.swing.JTextField();
        pinNumber = new javax.swing.JTextField();
        cardStatus = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        onButton = new javax.swing.JButton();
        adminScreen = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        idPassPanel.setBorder(new javax.swing.border.MatteBorder(null));

        cardNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cardNumber.setText("Enter Card Number");
        cardNumber.setToolTipText("Enter Card Number");
        cardNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardNumberFocusLost(evt);
            }
        });
        cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberActionPerformed(evt);
            }
        });
        cardNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardNumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cardNumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberKeyTyped(evt);
            }
        });

        pinNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pinNumber.setText("Enter PIN");
        pinNumber.setToolTipText("Enter Pin");
        pinNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pinNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pinNumberFocusLost(evt);
            }
        });
        pinNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinNumberActionPerformed(evt);
            }
        });
        pinNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pinNumberKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout idPassPanelLayout = new javax.swing.GroupLayout(idPassPanel);
        idPassPanel.setLayout(idPassPanelLayout);
        idPassPanelLayout.setHorizontalGroup(
            idPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPassPanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(idPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        idPassPanelLayout.setVerticalGroup(
            idPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPassPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(idPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardStatus))
                .addGap(18, 18, 18)
                .addComponent(pinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        enterButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        enterButton.setText("ENTER");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        onButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        onButton.setText("ON");
        onButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonActionPerformed(evt);
            }
        });

        adminScreen.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adminScreen.setText("ADMIN");
        adminScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminScreenActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel5.setText("ATM System by Aashna");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idPassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(enterButton)
                        .addGap(41, 41, 41)
                        .addComponent(onButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(adminScreen)
                        .addGap(37, 37, 37)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(idPassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinNumberActionPerformed

    private void cardNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNumberFocusGained
        // TODO add your handling code here:
        cardNumber.setText("");
    }//GEN-LAST:event_cardNumberFocusGained

    private void pinNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinNumberFocusGained
        // TODO add your handling code here:
        pinNumber.setText("");
    }//GEN-LAST:event_pinNumberFocusGained

    private void cardNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNumberFocusLost
        // TODO add your handling code here:
        if(cardNumber.getText().equals(""))
        {
            cardNumber.setText("Enter Card Number");
        }
    }//GEN-LAST:event_cardNumberFocusLost

    private void pinNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pinNumberFocusLost
        // TODO add your handling code here:
        if(pinNumber.getText().equals(""))
        {
            pinNumber.setText("Enter PIN");
        }
    }//GEN-LAST:event_pinNumberFocusLost

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void adminScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminScreenActionPerformed
        // TODO add your handling code here:
        AdminPanel ap=new AdminPanel();
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminScreenActionPerformed

    private void cardNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberKeyPressed
        int key=evt.getKeyCode();
        if((key>=KeyEvent.VK_0&&key<=KeyEvent.VK_9)||(key>=KeyEvent.VK_NUMPAD0&&key<=KeyEvent.VK_NUMPAD9)||key==KeyEvent.VK_BACKSPACE)
        {
            cardNumber.setEditable(true);
        }
        else
        {
            cardNumber.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberKeyPressed

    private void cardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberActionPerformed

    private void pinNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinNumberKeyPressed
        // TODO add your handling code here:
         int key=evt.getKeyCode();
        if((key>=evt.VK_0&&key<=evt.VK_9)||(key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACKSPACE)
        {
            pinNumber.setEditable(true);
        }
        else
        {
            pinNumber.setEditable(false);
        }
    }//GEN-LAST:event_pinNumberKeyPressed

    private void cardNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cardNumberKeyTyped

    private void cardNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberKeyReleased
        // TODO add your handling code here:
        StringBuilder content=new StringBuilder();
        content.append(cardNumber.getText());
        if(content.length()!=12)
        {
            cardStatus.setForeground(Color.red);
            cardStatus.setText("Invalid Card Number");
        }
        else
        {
            cardStatus.setForeground(Color.blue);
            cardStatus.setText("Valid");
        }
    }//GEN-LAST:event_cardNumberKeyReleased

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        String cardno=cardNumber.getText();
        String pin=pinNumber.getText();
        Card card=new Card();
        //if(cardNumber.getText().equals("123456123456") && pinNumber.getText().equals("4321") )
        if(card.verifyLogin(cardno, pin)==true)
        {
            LoginScreen ls=new LoginScreen(card);
            ls.setVisible(true);
            cardNumber.setText("Enter Card Number");
            cardStatus.setVisible(false);
            pinNumber.setText("Enter PIN");
            cardStatus.setText("");
            cardNumber.setVisible(false);
            pinNumber.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid Card Number or PIN","Invalid Credentials",1);
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void onButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonActionPerformed
        // TODO add your handling code here:
        cardNumber.setVisible(true);
        pinNumber.setVisible(true);
        cardStatus.setVisible(true);
    }//GEN-LAST:event_onButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminScreen;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JLabel cardStatus;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel idPassPanel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton onButton;
    private javax.swing.JTextField pinNumber;
    // End of variables declaration//GEN-END:variables
}
